### PR TITLE
Add support for Hyprland persistent workspace rules, fix config values not getting used, general improvements

### LINKED ISSUE #13: Where to set the config value?
I've tried setting it in `hyprland.conf` at `plugins` 

```
plugin {
  hyperload {
    config = "~/.config/hypr/hyprload.toml"
  },
  split-monitor-workspaces {
    count: 5,
  }
}
```

as well as in `hyprload.toml`
```
[split-monitor-workspaces]
count = 5
```

but none of these methods work

### PR DESCRIPTION
**Pull request by zjeffer**
* Add support for Hyprland persistent workspace rules
* Fix config values not getting used (fixes #13)
* Fix workspaces not being moved to correct monitor
* Added `.vscode` and `compile_commands.json` (generated by clangd) to `.gitignore`
* More logging
* General improvements
* Fix build since Hyprland v38 changes (PHLWORKSPACE error) (#58)

The persistent workspace rules are written to /tmp/hyprland-workspace-rules. This file can be loaded in your Hyprland config like this: https://github.com/zjeffer/dotfiles/blob/afd7c436d514f151c79b84cf732ab70c538c79fe/.config/hypr/configs/workspace_rules.conf#L1-L2
This can be used in combination with Waybar (since [this PR](https://github.com/Alexays/Waybar/pull/2603)), to dynamically make all your workspaces persistent.

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -177,19 +228,22 @@ APICALL EXPORT PLUGIN_DESCRIPTION_INFO PLUGIN_INIT(HANDLE handle)
     HyprlandAPI::addDispatcher(PHANDLE, "split-changemonitorsilent", splitChangeMonitorSilent);
 
     HyprlandAPI::reloadConfig();
+    g_pConfigManager->tick();
```
Comment (zjeffer) [inline src/main.cpp:231]: FYI: This line fixes #13.

**Comment by p-hannemann** [comment]
I am using this PR, and everything works flawlessly!
Great integration with waybar, would love to see this merged @Duckonaut :+1:

**Review by p-hannemann — APPROVED** [review]

**Comment by Duckonaut** [comment]
> Latest commit now fixes the build with Hyprland v38
> 
> @Duckonaut Have you abandoned this project? If so, I'd love to become a maintainer and take over development (I swear I'm not Jia Tan 😉). Lots of people are reporting issues but they are not being fixed, despite many PRs being made.

Yeah, sorry about that, I lost track of this project a bit since I wasn't updating my Hyprland and keeping up with the changes. I'll merge this PR out of the choices, also I will give you perms in the repo since you've contributed before (just don't go around doing supply chain attacks :+1:)

**Comment by Duckonaut** [comment]
@zjeffer the commit  dfbaf428cb1c1c6885de2ebe6f0e4777e92900d9 seems to be causing errors when running 0.38.1. Are those changes introduced later?

**Comment by zjeffer** [comment]
I'm on 20899d0df2a2811d83b4ae3357ad31a94eafcd8e.

Looks like the changes I merged will only work when using Hyprland from [this commit](https://github.com/hyprwm/Hyprland/commit/ef23ef60c5641c5903f9cf40571ead7ad6aba1b9) or later. We should preferably use `hyprpm`'s [commit pins feature](https://wiki.hyprland.org/Plugins/Development/Plugin-Guidelines/#commit-pins).

**Comment by Duckonaut** [comment]
oh yeah, that should solve it. The last good commit for 0.38.1 seems to be e05ca9d77a67a43244650d4afbe63b173214e9d8, I'll go pin it
